name: Build

on: [push, pull_request]

jobs:
    production-build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: pnpm/action-setup@v2
              with:
                  version: 7
            - uses: oven-sh/setup-bun@v1
              with:
                  bun-version: latest
            - run: bun install --no-frozen-lockfile
            - run: bun run build
